#!/bin/bash

alias copy='xsel -ib'
alias intellij='idea.sh &'
alias tunnel='ngrok http -subdomain=mongodb-cloud-emily-pakulski 8080'
alias authcode='oathtool --base32 --totp "MP2P2JN7736JFXHB"'

MMS_DEBUG_ARGS='-Djvm.debug.suspend=n -Djvm.debug.port=5005 -Djvm.debug=y'
DAEMON_DEBUG_ARGS='-Djvm.debug.suspend=n -Djvm.debug.port=5006 -Djvm.debug=y'

ANT_OM='ant mms.server.hosted'
OM_OUT_PREFIX='sed "s/^/[mms-om] /"'
ANT_OM_DAEMON='ant daemon.hosted'
OM_DAEMON_OUT_PREFIX='sed "s/^/[dmn-om] /"'

alias om="$ANT_OM | $OM_OUT_PREFIX"
alias om.debug="$ANT_OM $MMS_DEBUG_ARGS | $OM_OUT_PREFIX"
alias omd="$ANT_OM_DAEMON | $OM_DAEMON_OUT_PREFIX"
alias omd.debug="$ANT_OM_DAEMON $DAEMON_DEBUG_ARGS | $OM_DAEMON_OUT_PREFIX"

ANT_CM='ant mms.server.local'
CM_OUT_PREFIX='sed "s/^/mms-cm] /"'
ANT_CM_DAEMON='ant daemon.local'
CM_DAEMON_OUT_PREFIX='sed "s/^/[dmn-cm] /"'

alias cm="$ANT_CM | $CM_OUT_PREFIX"
alias cm.debug="$ANT_CM $MMS_DEBUG_ARGS | $CM_OUT_PREFIX"
alias cmd="$ANT_CM_DAEMON | $CM_DAEMON_OUT_PREFIX"
alias cmd.debug="$ANT_CM_DAEMON $DAEMON_DEBUG_ARGS | $CM_DAEMON_OUT_PREFIX"
